### ISSUE TITLE
70RC4 Translation

### ISSUE THREAD

**Issue by PatriceTorchet** [abstractspoon/ToDoList_Issues#25]
In RC4 and earlier.
After TDL updated the dictionary of French translation,
"Change l’icône de l’objet sélectionné\nChanger l’icône"	""	"text"
which is the translation of
"Change icon of selected object\nChange Icon"	""	"text"
keeps coming back into the translation file.

same for
"Active l’objet incorporé ou lié"	""	"text"
which is the translation of
"Activate embedded or linked object"	""	"text"

same for
"Liste de Tâches (*.tdl, *.xml)"	""	"combobox.1136"
which is the translation of
"Tasklist (*.tdl, *.xml)"	""	"combobox.1136"

**Comment by abstractspoon** [comment]
I couldn't find either of those strings used anywhere in the application so I have removed them from the translation files.

**Comment by PatriceTorchet** [comment]
Ok
You checked the 3 ?

**Comment by abstractspoon** [comment]
No, I missed the last one.

**Comment by abstractspoon** [comment]
ps. I suggest not closing the issue until you are satisfied after the next update

**Comment by Pierre-de-la-Verre** [comment]
Hi Patrice
you mean that French strings appear in the "Need_Translation" to be translated?
If yes - I know that the behaviour is not correct, but it happens since long time and I don't care about it. Also strings from the Comments appear in the Need_translation. I remove them manually or with "Clean up", that's all.

**Comment by Pierre-de-la-Verre** [comment]
Hi Patrice
can it be closed?

**Comment by abstractspoon** [comment]
More fixed in 7.0.1 ;)
